#!/bin/bash
MPLBACKEND=qt5agg

FILE="$(zenity --file-selection --title='Select a model file')"
case $? in
    0)
        echo using $FILE;;
    1)
        zenity --question \
               --title="Sandbox" \
               --text="No file selected. Do you want to select one?" \
            && choose-file \
                || exit;;
    -1)
        echo "An unexpected error has occurred.";
        exit;;
esac
zenity --question --text="Do you want to use mmi?"
case $? in
    0)
        MMI=yes
        echo using mmi $MMI ;;
    1)
        MMI=no
        echo not using mmi $MMI ;;
    -1)
        echo "An unexpected error has occurred.";
        exit;;
esac

# mmi runner dflowfm models/Waal_schematic/waal_with_side.mdu --port 62000 --pause -o s1 -o bl -o ucx -o ucy -o zk &
# sandbox-fm run --mmi tcp://localhost:62000  $filename &
# move sandbox to correct screen

# list all windows
# wmctrl -l
# pick the with the sandbox, store in $win

# wmctrl -r sandbox-fm -b remove,fullscreen

# Select window for actions
# wmctrl -r $win
# Switch to desktop 2
# wmctrl -s 2
# move window to current desktop
# wmctrl -R $win
# wmctrl -a
